language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install pyxb
  - pip install -e .
  - pip install pytest-cov
  - pip install PyGithub==1.39
  - pip install flake8==3.4.1

before_script:
  - flake8 --count --ignore W503,F401 --exclude teaser/data/bindings,doc,tests --max-line-length=120

script:
- py.test --cov=teaser


